---
booktitle: "Proceedings of the Twelfth Symposium on Conformal\r and Probabilistic
  Prediction with Applications"
shortname: COPA 2023
volume: '204'
year: '2023'
start: 2023-09-13
end: 2023-09-15
published: 2023-08-17
url: https://proceedings.mlr.press
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: COPA-2023
month: 0
cycles: false
bibtex_editor: Papadopoulos, Harris and Nguyen, Khuong An and Bostr\"{o}m, Henrik
  and Carlsson, Lars
editor:
- given: Harris
  family: Papadopoulos
- given: Khuong An
  family: Nguyen
- given: Henrik
  family: Boström
- given: Lars
  family: Carlsson
title: Proceedings of Machine Learning Research
description: "Proceedings of the Twelfth Symposium on Conformal\r and Probabilistic
  Prediction with Applications\n  Held in Limassol, Cyprus on 13-15 September 2023\n\nPublished
  as Volume 204 by the Proceedings of Machine Learning Research on 17 August 2023.\n\nVolume
  Edited by:\n  Harris Papadopoulos\n  Khuong An Nguyen\n  Henrik Boström\n  Lars
  Carlsson\n\nSeries Editors:\n  Neil D. Lawrence\n"
date_str: 13--15 Sep
author:
  name: PMLR
baseurl: "/v204"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v204
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v204
email: ''
conference:
  name: "Conformal and Probabilistic Prediction with\r Applications"
  url:
  location: Limassol, Cyprus
  dates:
  - 2023-09-13
  - 2023-09-14
  - 2023-09-15
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v204/copa23.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v204/copa23.bib
